server:
  port: 8078

spring:
  datasource:
    username: yebiaocat
    password: 123456
    url: jdbc:mysql://localhost:3306/yecat?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/*Mappers.xml
  type-aliases-package: cn.yb.democat.entity

